title: Application
x-stoplight:
  id: dldt12jdx1x5i
type: object
description: Represents an application that interfaces with the REST API to access accounts or post statuses.
examples:
  - name: test app
    website: null
    vapid_key: BCk-QqERU0q-CfYZjcuB6lnyyOYfJ2AifKqfeGIm7Z-HiTU5T9eTG5GxVA0_OH5mMlI4UkkDTpaZwozy0TzdZ2M=
properties:
  name:
    type: string
    description: The name of your application.
  website:
    type: string
    nullable: true
    description: The website associated with your application.
    format: uri
  vapid_key:
    type: string
    description: ' Used for Push Streaming API. Returned with POST /api/v1/apps. Equivalent to PushSubscription#server_key.'
required:
  - name